# edit in mprove-api only

# see vscode settings prettier.*
# https://github.com/prettier/prettier-vscode

arrowParens: avoid
bracketSpacing: true
endOfLine: lf # default: auto
htmlWhitespaceSensitivity: css
jsxBracketSameLine: true # default: false
# jsxSingleQuote: false
# parser: babylon
printWidth: 80 # default: 80
proseWrap: preserve
semi: true
singleQuote: true # default: false
tabWidth: 2
trailingComma: none
useTabs: false

# prettier.eslintIntegration
# prettier.tslintIntegration
# prettier.stylelintIntegration
# prettier.requireConfig
# prettier.ignorePath
# prettier.disableLanguages - used in vscode settings