default: # default connection
  type: mysql
  host: db
  port: 3306
  username: root
  password: root
  database: my_db
  charset: utf8mb4
  logging: true
  logger: file
  entities: 
  - src/models/store/entities/*.ts # CLI loads from ts files when use ts-node
  migrations: 
  - src/migration/*.ts # CLI loads from ts files when use ts-node
  cli: 
    entitiesDir: src/models/store/entities # CLI created entities to folder
    migrationsDir: src/migration # CLI created migrations to folder