version: '3.7'
services:
  db:
    image: mysql:5.7.25
    volumes:
      - type: bind
        source: /mprove_data/db/mysql
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - '3305:3306'

  redis:
    image: redis:alpine

  blockml:
    image: mprove/mprove-ce-blockml:$MPROVE_CE_RELEASE_TAG

  backend:
    image: mprove/mprove-ce-backend:$MPROVE_CE_RELEASE_TAG
    environment:
      BACKEND_DATABASE_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      BACKEND_DATABASE: $MYSQL_DATABASE      
      BACKEND_DROP_DATABASE_ON_START: $BACKEND_DROP_DATABASE_ON_START    
      BACKEND_JWT_SECRET: $BACKEND_JWT_SECRET
      BACKEND_FIRST_USER_EMAIL: $BACKEND_FIRST_USER_EMAIL
      BACKEND_FIRST_USER_PASSWORD: $BACKEND_FIRST_USER_PASSWORD
      BACKEND_REGISTER_ONLY_INVITED_USERS: $BACKEND_REGISTER_ONLY_INVITED_USERS      
      BACKEND_MAILGUN_ACTIVE_API_KEY: $BACKEND_MAILGUN_ACTIVE_API_KEY
      BACKEND_MAILGUN_DOMAIN: $BACKEND_MAILGUN_DOMAIN
      BACKEND_SEND_EMAIL_FROM: $BACKEND_SEND_EMAIL_FROM
    volumes:
      - type: bind
        source: /mprove_data/backend
        target: /mprove_data/backend

  client:
    image: mprove/mprove-ce-client-local:$MPROVE_CE_RELEASE_TAG

  proxy:
    image: mprove/mprove-ce-proxy-local:$MPROVE_CE_RELEASE_TAG
    ports:
      - '80:80'
      - '8080:80'

